CHALLENGE_DATA_DIR: "datasets/Dataset_A"
DET_SOURCE_DIR: "datasets/detection/validation/S05"
DATA_DIR: "datasets/detect/"
REID_SIZE_TEST: [384, 384]
ROI_DIR: "datasets/Dataset_A/validation/S05"
CID_BIAS_DIR: "datasets/Dataset_A/cam_timestamp/"
USE_RERANK: True
USE_FF: True
SCORE_THR: 0.1
MCMT_OUTPUT_TXT: "track1.txt"
MCMT_Interpo_OUTPUT_TXT: "track1_interpolation.txt"
