DET_SOURCE_DIR: "${ROOT}/datasets/detection/images/test/S06/"
REID_MODEL: "reid_model/resnext101_ibn_a_2.pth"
REID_BACKBONE: "resnext101_ibn_a"
DET_IMG_DIR: "${ROOT}/datasets/detect/"
DATA_DIR: "${ROOT}/datasets/detect_reid2/"
REID_SIZE_TEST: [384, 384]
