# Removes all the intermediate data generated by the pipeline
# Note: this takes about 30 minutes for the validation set

cd datasets

echo "Removing datasets/detect_reid1/*"
cd detect_reid1
rm -r *

echo "Removing datasets/detect_reid2/*"
cd ../detect_reid2
rm -r *

echo "Removing datasets/detect_reid3/*"
cd ../detect_reid3
rm -r *

echo "Removing datasets/detection/*"
cd ../detection
rm -r *

echo "Removing datasets/detect/*"
cd ../detect
rm -r *

echo "Removing reid_bidir/reid-matching/tools/local_to_universal_map.pkl"
cd ../../reid_bidir/reid-matching/tools
rm local_to_universal_map.pkl

echo "Removing reid_bidir/reid-matching/tools/exp/viz/validation/S05/movement/*"
cd exp/viz/validation/S05/movement
rm *

echo "Removing reid_bidir/reid-matching/tools/exp/viz/validation/S05/trajectory/*"
cd ../trajectory
rm *