# Removes all the intermediate data generated by the pipeline
# Note: this takes about 30 minutes for the validation set

cd datasets

cd detect_reid1
rm -r *

cd ../detect_reid2
rm -r *

cd ../detect_reid3
rm -r *

cd ../detection
rm -r *

cd ../detect
rm -r *

cd ../../reid_bidir/reid-matching/tools
rm test_cluster.py

cd exp/viz/validation/S05
rm *